
deploy:
  stage: deploy
  variables:
    HEROKU_APP: siimleaksbasic
  only:
    - main
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_PRODUCTION_API_KEY