image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: sanderknape/go-hello-world:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} sanderknape/go-hello-world:latest
    - docker push ${CONTAINER_IMAGE}

image: registry.gitlab.com/xa-online-2021-march/builder:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - kubectl apply -f deployment.yaml
  only:
    - master