kind: Namespace
apiVersion: v1
metadata:
  name: siim-aarmaa
  labels: 
    name: siim-aarmaa
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: siim-config
  namespace: siim-aarmaa
data:
  happy: "true"
  message: "I love pets"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "example-deployment"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "petclinic"
    spec:
      containers:
        - image: 647773465573.dkr.ecr.eu-west-1.amazonaws.com/spring-petclinic:HEAD.2.8399c7b
          imagePullPolicy: Always
          name: "petclinic"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: "example-service"
  namespace: "example"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "petclinic"
