name: Publish Docker image to DigitalOcean Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker config
      - name: Set up Docker config
        run: |
          mkdir -p $HOME/.docker
          echo '${{ secrets.DOCKER_CONFIG_JSON }}' > $HOME/.docker/config.json

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/tourepo/discord_bot:latest .

      # Step 5: Push Docker image to DigitalOcean Container Registry
      - name: Push Docker image
        run: docker push registry.digitalocean.com/tourepo/discord_bot:latest