name: Build and Push Docker Image to DigitalOcean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to DigitalOcean Container Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/siimleaksbasic:latest .
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

    - name: Push Docker image to DigitalOcean
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/siimleaksbasic:latest
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
