name: Automated Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Read Changelog
      id: read_changelog
      run: |
        echo "::set-output name=changelog::$(cat CHANGELOG.md)"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract_branch.outputs.branch }}
        release_name: Release ${{ steps.extract_branch.outputs.branch }}
        body: ${{ steps.read_changelog.outputs.changelog }}
        draft: false
        prerelease: false
